package com.cisco.la.mapper;

import com.cisco.la.model.FlyerModel;
import com.cisco.la.model.FlyerModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlyerModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	long countByExample(FlyerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int deleteByExample(FlyerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int insert(FlyerModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int insertSelective(FlyerModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	List<FlyerModel> selectByExample(FlyerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	FlyerModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int updateByExampleSelective(@Param("record") FlyerModel record, @Param("example") FlyerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int updateByExample(@Param("record") FlyerModel record, @Param("example") FlyerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int updateByPrimaryKeySelective(FlyerModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_flyer
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	int updateByPrimaryKey(FlyerModel record);
}