package com.cisco.la.mapper;

import com.cisco.la.model.RecordModel;
import com.cisco.la.model.RecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	long countByExample(RecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int deleteByExample(RecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int insert(RecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int insertSelective(RecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	List<RecordModel> selectByExample(RecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	RecordModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int updateByExampleSelective(@Param("record") RecordModel record, @Param("example") RecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int updateByExample(@Param("record") RecordModel record, @Param("example") RecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int updateByPrimaryKeySelective(RecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_record
	 * @mbg.generated  Wed Mar 14 16:19:03 CST 2018
	 */
	int updateByPrimaryKey(RecordModel record);
}