package com.cisco.la.model;

import java.util.Date;

public class FlyerModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_id
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_content
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_active_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private Date activeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_audience_type
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private String audienceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_audience_list
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private String audienceList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_active
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_flyer.flr_update_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_id
     *
     * @return the value of public.la_flyer.flr_id
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_id
     *
     * @param id the value for public.la_flyer.flr_id
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_content
     *
     * @return the value of public.la_flyer.flr_content
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_content
     *
     * @param content the value for public.la_flyer.flr_content
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_active_time
     *
     * @return the value of public.la_flyer.flr_active_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_active_time
     *
     * @param activeTime the value for public.la_flyer.flr_active_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_audience_type
     *
     * @return the value of public.la_flyer.flr_audience_type
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public String getAudienceType() {
        return audienceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_audience_type
     *
     * @param audienceType the value for public.la_flyer.flr_audience_type
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setAudienceType(String audienceType) {
        this.audienceType = audienceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_audience_list
     *
     * @return the value of public.la_flyer.flr_audience_list
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public String getAudienceList() {
        return audienceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_audience_list
     *
     * @param audienceList the value for public.la_flyer.flr_audience_list
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setAudienceList(String audienceList) {
        this.audienceList = audienceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_active
     *
     * @return the value of public.la_flyer.flr_active
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_active
     *
     * @param active the value for public.la_flyer.flr_active
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_flyer.flr_update_time
     *
     * @return the value of public.la_flyer.flr_update_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_flyer.flr_update_time
     *
     * @param updateTime the value for public.la_flyer.flr_update_time
     *
     * @mbg.generated Tue Apr 03 13:57:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}