package com.cisco.la.model;

import java.util.Date;

public class GoldenSampleModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private int id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String goldenSampleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer roleID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_mandatory
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String mandatory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_optional
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String optional;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_golden_sample.smpl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Boolean active;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_id
	 * @return  the value of public.la_golden_sample.smpl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public int getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_id
	 * @param id  the value for public.la_golden_sample.smpl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_name
	 * @return  the value of public.la_golden_sample.smpl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getGoldenSampleName() {
		return goldenSampleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_name
	 * @param goldenSampleName  the value for public.la_golden_sample.smpl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setGoldenSampleName(String goldenSampleName) {
		this.goldenSampleName = goldenSampleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_rl_id
	 * @return  the value of public.la_golden_sample.smpl_rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getRoleID() {
		return roleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_rl_id
	 * @param roleID  the value for public.la_golden_sample.smpl_rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setRoleID(Integer roleID) {
		this.roleID = roleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_mandatory
	 * @return  the value of public.la_golden_sample.smpl_mandatory
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getMandatory() {
		return mandatory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_mandatory
	 * @param mandatory  the value for public.la_golden_sample.smpl_mandatory
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setMandatory(String mandatory) {
		this.mandatory = mandatory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_optional
	 * @return  the value of public.la_golden_sample.smpl_optional
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getOptional() {
		return optional;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_optional
	 * @param optional  the value for public.la_golden_sample.smpl_optional
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setOptional(String optional) {
		this.optional = optional;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_update_time
	 * @return  the value of public.la_golden_sample.smpl_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_update_time
	 * @param updateTime  the value for public.la_golden_sample.smpl_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_golden_sample.smpl_active
	 * @return  the value of public.la_golden_sample.smpl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_golden_sample.smpl_active
	 * @param active  the value for public.la_golden_sample.smpl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}
}