package com.cisco.la.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public MessageModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("msg_id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("msg_id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("msg_id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("msg_id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("msg_id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("msg_id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("msg_id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("msg_id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("msg_id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("msg_id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("msg_id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("msg_id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIDIsNull() {
			addCriterion("msg_user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIDIsNotNull() {
			addCriterion("msg_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIDEqualTo(String value) {
			addCriterion("msg_user_id =", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotEqualTo(String value) {
			addCriterion("msg_user_id <>", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThan(String value) {
			addCriterion("msg_user_id >", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThanOrEqualTo(String value) {
			addCriterion("msg_user_id >=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThan(String value) {
			addCriterion("msg_user_id <", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThanOrEqualTo(String value) {
			addCriterion("msg_user_id <=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLike(String value) {
			addCriterion("msg_user_id like", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotLike(String value) {
			addCriterion("msg_user_id not like", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDIn(List<String> values) {
			addCriterion("msg_user_id in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotIn(List<String> values) {
			addCriterion("msg_user_id not in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDBetween(String value1, String value2) {
			addCriterion("msg_user_id between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotBetween(String value1, String value2) {
			addCriterion("msg_user_id not between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("msg_content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("msg_content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("msg_content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("msg_content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("msg_content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("msg_content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("msg_content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("msg_content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("msg_content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("msg_content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("msg_content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("msg_content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("msg_content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("msg_content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andSerialIsNull() {
			addCriterion("msg_serial is null");
			return (Criteria) this;
		}

		public Criteria andSerialIsNotNull() {
			addCriterion("msg_serial is not null");
			return (Criteria) this;
		}

		public Criteria andSerialEqualTo(Integer value) {
			addCriterion("msg_serial =", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotEqualTo(Integer value) {
			addCriterion("msg_serial <>", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialGreaterThan(Integer value) {
			addCriterion("msg_serial >", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialGreaterThanOrEqualTo(Integer value) {
			addCriterion("msg_serial >=", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialLessThan(Integer value) {
			addCriterion("msg_serial <", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialLessThanOrEqualTo(Integer value) {
			addCriterion("msg_serial <=", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialIn(List<Integer> values) {
			addCriterion("msg_serial in", values, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotIn(List<Integer> values) {
			addCriterion("msg_serial not in", values, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialBetween(Integer value1, Integer value2) {
			addCriterion("msg_serial between", value1, value2, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotBetween(Integer value1, Integer value2) {
			addCriterion("msg_serial not between", value1, value2, "serial");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("msg_level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("msg_level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value) {
			addCriterion("msg_level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value) {
			addCriterion("msg_level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value) {
			addCriterion("msg_level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("msg_level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value) {
			addCriterion("msg_level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value) {
			addCriterion("msg_level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values) {
			addCriterion("msg_level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values) {
			addCriterion("msg_level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2) {
			addCriterion("msg_level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("msg_level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("msg_create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("msg_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("msg_create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("msg_create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("msg_create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("msg_create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("msg_create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("msg_create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("msg_create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("msg_create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("msg_create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("msg_create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andActiveIsNull() {
			addCriterion("msg_active is null");
			return (Criteria) this;
		}

		public Criteria andActiveIsNotNull() {
			addCriterion("msg_active is not null");
			return (Criteria) this;
		}

		public Criteria andActiveEqualTo(Boolean value) {
			addCriterion("msg_active =", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotEqualTo(Boolean value) {
			addCriterion("msg_active <>", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThan(Boolean value) {
			addCriterion("msg_active >", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("msg_active >=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThan(Boolean value) {
			addCriterion("msg_active <", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("msg_active <=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveIn(List<Boolean> values) {
			addCriterion("msg_active in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotIn(List<Boolean> values) {
			addCriterion("msg_active not in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("msg_active between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("msg_active not between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andSessionIsNull() {
			addCriterion("msg_session is null");
			return (Criteria) this;
		}

		public Criteria andSessionIsNotNull() {
			addCriterion("msg_session is not null");
			return (Criteria) this;
		}

		public Criteria andSessionEqualTo(Integer value) {
			addCriterion("msg_session =", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotEqualTo(Integer value) {
			addCriterion("msg_session <>", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionGreaterThan(Integer value) {
			addCriterion("msg_session >", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionGreaterThanOrEqualTo(Integer value) {
			addCriterion("msg_session >=", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionLessThan(Integer value) {
			addCriterion("msg_session <", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionLessThanOrEqualTo(Integer value) {
			addCriterion("msg_session <=", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionIn(List<Integer> values) {
			addCriterion("msg_session in", values, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotIn(List<Integer> values) {
			addCriterion("msg_session not in", values, "session");
			return (Criteria) this;
		}

		public Criteria andSessionBetween(Integer value1, Integer value2) {
			addCriterion("msg_session between", value1, value2, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotBetween(Integer value1, Integer value2) {
			addCriterion("msg_session not between", value1, value2, "session");
			return (Criteria) this;
		}

		public Criteria andIntentIsNull() {
			addCriterion("msg_intent is null");
			return (Criteria) this;
		}

		public Criteria andIntentIsNotNull() {
			addCriterion("msg_intent is not null");
			return (Criteria) this;
		}

		public Criteria andIntentEqualTo(String value) {
			addCriterion("msg_intent =", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentNotEqualTo(String value) {
			addCriterion("msg_intent <>", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentGreaterThan(String value) {
			addCriterion("msg_intent >", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentGreaterThanOrEqualTo(String value) {
			addCriterion("msg_intent >=", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentLessThan(String value) {
			addCriterion("msg_intent <", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentLessThanOrEqualTo(String value) {
			addCriterion("msg_intent <=", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentLike(String value) {
			addCriterion("msg_intent like", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentNotLike(String value) {
			addCriterion("msg_intent not like", value, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentIn(List<String> values) {
			addCriterion("msg_intent in", values, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentNotIn(List<String> values) {
			addCriterion("msg_intent not in", values, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentBetween(String value1, String value2) {
			addCriterion("msg_intent between", value1, value2, "intent");
			return (Criteria) this;
		}

		public Criteria andIntentNotBetween(String value1, String value2) {
			addCriterion("msg_intent not between", value1, value2, "intent");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("msg_action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("msg_action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(String value) {
			addCriterion("msg_action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(String value) {
			addCriterion("msg_action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(String value) {
			addCriterion("msg_action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(String value) {
			addCriterion("msg_action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(String value) {
			addCriterion("msg_action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(String value) {
			addCriterion("msg_action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLike(String value) {
			addCriterion("msg_action like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotLike(String value) {
			addCriterion("msg_action not like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<String> values) {
			addCriterion("msg_action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<String> values) {
			addCriterion("msg_action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(String value1, String value2) {
			addCriterion("msg_action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(String value1, String value2) {
			addCriterion("msg_action not between", value1, value2, "action");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.la_message
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_message
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 05 16:53:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}