package com.cisco.la.model;

import java.util.Date;

public class PaperModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_quz_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer quizID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_usr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String userID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_content
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_standard
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String standard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_answer
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String awswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_score
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_total
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_index
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Integer index;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_session
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Date session;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_paper.ppr_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Boolean active;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_id
	 * @return  the value of public.la_paper.ppr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_id
	 * @param id  the value for public.la_paper.ppr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_quz_id
	 * @return  the value of public.la_paper.ppr_quz_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getQuizID() {
		return quizID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_quz_id
	 * @param quizID  the value for public.la_paper.ppr_quz_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setQuizID(Integer quizID) {
		this.quizID = quizID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_usr_id
	 * @return  the value of public.la_paper.ppr_usr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getUserID() {
		return userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_usr_id
	 * @param userID  the value for public.la_paper.ppr_usr_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_content
	 * @return  the value of public.la_paper.ppr_content
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_content
	 * @param content  the value for public.la_paper.ppr_content
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_standard
	 * @return  the value of public.la_paper.ppr_standard
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getStandard() {
		return standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_standard
	 * @param standard  the value for public.la_paper.ppr_standard
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setStandard(String standard) {
		this.standard = standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_answer
	 * @return  the value of public.la_paper.ppr_answer
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getAwswer() {
		return awswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_answer
	 * @param awswer  the value for public.la_paper.ppr_answer
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setAwswer(String awswer) {
		this.awswer = awswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_update_time
	 * @return  the value of public.la_paper.ppr_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_update_time
	 * @param updateTime  the value for public.la_paper.ppr_update_time
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_score
	 * @return  the value of public.la_paper.ppr_score
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_score
	 * @param score  the value for public.la_paper.ppr_score
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_total
	 * @return  the value of public.la_paper.ppr_total
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_total
	 * @param total  the value for public.la_paper.ppr_total
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setTotal(Integer total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_index
	 * @return  the value of public.la_paper.ppr_index
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Integer getIndex() {
		return index;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_index
	 * @param index  the value for public.la_paper.ppr_index
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setIndex(Integer index) {
		this.index = index;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_session
	 * @return  the value of public.la_paper.ppr_session
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Date getSession() {
		return session;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_session
	 * @param session  the value for public.la_paper.ppr_session
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setSession(Date session) {
		this.session = session;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_paper.ppr_active
	 * @return  the value of public.la_paper.ppr_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_paper.ppr_active
	 * @param active  the value for public.la_paper.ppr_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}
}