package com.cisco.la.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public QuestionModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andQuizIDIsNull() {
			addCriterion("qust_quiz_id is null");
			return (Criteria) this;
		}

		public Criteria andQuizIDIsNotNull() {
			addCriterion("qust_quiz_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuizIDEqualTo(Integer value) {
			addCriterion("qust_quiz_id =", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDNotEqualTo(Integer value) {
			addCriterion("qust_quiz_id <>", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDGreaterThan(Integer value) {
			addCriterion("qust_quiz_id >", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("qust_quiz_id >=", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDLessThan(Integer value) {
			addCriterion("qust_quiz_id <", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDLessThanOrEqualTo(Integer value) {
			addCriterion("qust_quiz_id <=", value, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDIn(List<Integer> values) {
			addCriterion("qust_quiz_id in", values, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDNotIn(List<Integer> values) {
			addCriterion("qust_quiz_id not in", values, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDBetween(Integer value1, Integer value2) {
			addCriterion("qust_quiz_id between", value1, value2, "quizID");
			return (Criteria) this;
		}

		public Criteria andQuizIDNotBetween(Integer value1, Integer value2) {
			addCriterion("qust_quiz_id not between", value1, value2, "quizID");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("qust_subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("qust_subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("qust_subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("qust_subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("qust_subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("qust_subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("qust_subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("qust_subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("qust_subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("qust_subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("qust_subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("qust_subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("qust_subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("qust_subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andChoicesIsNull() {
			addCriterion("qust_choices is null");
			return (Criteria) this;
		}

		public Criteria andChoicesIsNotNull() {
			addCriterion("qust_choices is not null");
			return (Criteria) this;
		}

		public Criteria andChoicesEqualTo(String value) {
			addCriterion("qust_choices =", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesNotEqualTo(String value) {
			addCriterion("qust_choices <>", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesGreaterThan(String value) {
			addCriterion("qust_choices >", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesGreaterThanOrEqualTo(String value) {
			addCriterion("qust_choices >=", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesLessThan(String value) {
			addCriterion("qust_choices <", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesLessThanOrEqualTo(String value) {
			addCriterion("qust_choices <=", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesLike(String value) {
			addCriterion("qust_choices like", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesNotLike(String value) {
			addCriterion("qust_choices not like", value, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesIn(List<String> values) {
			addCriterion("qust_choices in", values, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesNotIn(List<String> values) {
			addCriterion("qust_choices not in", values, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesBetween(String value1, String value2) {
			addCriterion("qust_choices between", value1, value2, "choices");
			return (Criteria) this;
		}

		public Criteria andChoicesNotBetween(String value1, String value2) {
			addCriterion("qust_choices not between", value1, value2, "choices");
			return (Criteria) this;
		}

		public Criteria andAnswerIsNull() {
			addCriterion("qust_answer is null");
			return (Criteria) this;
		}

		public Criteria andAnswerIsNotNull() {
			addCriterion("qust_answer is not null");
			return (Criteria) this;
		}

		public Criteria andAnswerEqualTo(String value) {
			addCriterion("qust_answer =", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerNotEqualTo(String value) {
			addCriterion("qust_answer <>", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerGreaterThan(String value) {
			addCriterion("qust_answer >", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerGreaterThanOrEqualTo(String value) {
			addCriterion("qust_answer >=", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerLessThan(String value) {
			addCriterion("qust_answer <", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerLessThanOrEqualTo(String value) {
			addCriterion("qust_answer <=", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerLike(String value) {
			addCriterion("qust_answer like", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerNotLike(String value) {
			addCriterion("qust_answer not like", value, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerIn(List<String> values) {
			addCriterion("qust_answer in", values, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerNotIn(List<String> values) {
			addCriterion("qust_answer not in", values, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerBetween(String value1, String value2) {
			addCriterion("qust_answer between", value1, value2, "answer");
			return (Criteria) this;
		}

		public Criteria andAnswerNotBetween(String value1, String value2) {
			addCriterion("qust_answer not between", value1, value2, "answer");
			return (Criteria) this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("qust_number is null");
			return (Criteria) this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("qust_number is not null");
			return (Criteria) this;
		}

		public Criteria andNumberEqualTo(Integer value) {
			addCriterion("qust_number =", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotEqualTo(Integer value) {
			addCriterion("qust_number <>", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThan(Integer value) {
			addCriterion("qust_number >", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("qust_number >=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThan(Integer value) {
			addCriterion("qust_number <", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThanOrEqualTo(Integer value) {
			addCriterion("qust_number <=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberIn(List<Integer> values) {
			addCriterion("qust_number in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotIn(List<Integer> values) {
			addCriterion("qust_number not in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberBetween(Integer value1, Integer value2) {
			addCriterion("qust_number between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("qust_number not between", value1, value2, "number");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.la_question
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_question
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 07 15:35:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}