package com.cisco.la.model;

import java.util.Date;

public class RoleHistoryModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_rl_history.hstr_usr_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	private String userID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_rl_history.hstr_rl_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	private Integer roleID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_rl_history.hstr_update_time
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_rl_history.hstr_usr_id
	 * @return  the value of public.la_rl_history.hstr_usr_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public String getUserID() {
		return userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_rl_history.hstr_usr_id
	 * @param userID  the value for public.la_rl_history.hstr_usr_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_rl_history.hstr_rl_id
	 * @return  the value of public.la_rl_history.hstr_rl_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public Integer getRoleID() {
		return roleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_rl_history.hstr_rl_id
	 * @param roleID  the value for public.la_rl_history.hstr_rl_id
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void setRoleID(Integer roleID) {
		this.roleID = roleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_rl_history.hstr_update_time
	 * @return  the value of public.la_rl_history.hstr_update_time
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_rl_history.hstr_update_time
	 * @param updateTime  the value for public.la_rl_history.hstr_update_time
	 * @mbg.generated  Thu Apr 12 17:19:19 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}