package com.cisco.la.model;

public class RoleModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private int id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_bu
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String bu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_title
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_grade
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.la_role.rl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	private Boolean active;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_id
	 * @return  the value of public.la_role.rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public int getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_id
	 * @param id  the value for public.la_role.rl_id
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_name
	 * @return  the value of public.la_role.rl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_name
	 * @param roleName  the value for public.la_role.rl_name
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_bu
	 * @return  the value of public.la_role.rl_bu
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getBu() {
		return bu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_bu
	 * @param bu  the value for public.la_role.rl_bu
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setBu(String bu) {
		this.bu = bu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_title
	 * @return  the value of public.la_role.rl_title
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_title
	 * @param title  the value for public.la_role.rl_title
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_grade
	 * @return  the value of public.la_role.rl_grade
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_grade
	 * @param grade  the value for public.la_role.rl_grade
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.la_role.rl_active
	 * @return  the value of public.la_role.rl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.la_role.rl_active
	 * @param active  the value for public.la_role.rl_active
	 * @mbg.generated  Tue Apr 03 13:57:50 CST 2018
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}
}